services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pg_network

  flyway:
    image: flyway/flyway:10
    container_name: flyway_migrations
    depends_on:
      - postgres
    command: >
      -url=jdbc:postgresql://postgres:5432/mydb -user=admin -password=admin123
      -schemas=receta,userSchema -connectRetries=60 migrate
    volumes:
      # carpeta local donde tendrás tus migraciones
      - ./migrations:/flyway/sql
    networks:
      - pg_network

volumes:
  postgres_data:

networks:
  pg_network:
    driver: bridge
